keyMirror = require 'keymirror'

module.exports = keyMirror
#signaling events
  EVENT_LOCAL_USER_AUTHENTICATED: null
  EVENT_REMOTE_USER_LOGGED_ON: null
  EVENT_REMOTE_USER_LOGGED_OFF: null
  EVENT_REMOTE_DESCRIPTION_RECEIVED: null
  EVENT_REMOTE_ICE_CANDIDATE_RECEIVED: null
  EVENT_SOCKET_CONNECTION_LOST: null
#peer manager & peer
  EVENT_PEER_CREATED: null
  EVENT_PEER_REMOVED: null
  EVENT_PEER_STATUS_CHANGED: null
  EVENT_PEER_SMP_STATUS_CHANGED: null
  EVENT_PEER_LOCAL_ICE_CANDIDATE: null
  EVENT_PEER_LOCAL_DESCRIPTION: null
#peer stati
  PEER_STATUS_CONNECTING: null
  PEER_STATUS_CONNECTED: null
  PEER_STATUS_DISCONNECTED: null
  PEER_STATUS_SECURE_LINE: null
  PEER_SMP_STATUS_NOTHING: null
  PEER_SMP_STATUS_ASKING: null
  PEER_SMP_STATUS_ABORTED: null
  PEER_SMP_STATUS_VERIFIED: null
  PEER_SMP_STATUS_FALSIFIED: null
#user stati
  USER_STATUS_FRESH: null
  USER_STATUS_GENERATING_KEY: null
  USER_STATUS_AUTHENTICATING: null
  USER_STATUS_AUTHENTICATED_ON_SERVER: null
  USER_STATUS_SETUP_COMPLETE: null
#dispatcher action types
  ACTIONTYPE_MESSAGE_OUTBOUND: null
  ACTIONTYPE_MESSAGE_INBOUND: null
  ACTIONTYPE_USERNAME_SUPPLIED: null
  ACTIONTYPE_SHOW_VERIFICATION_BOX: null
  ACTIONTYPE_CLOSE_VERIFICATION_BOX: null
  ACTIONTYPE_VERIFY_PEER: null
  ACTIONTYPE_UNVERIFY_PEER: null
  ACTIONTYPE_SMP_INBOUND: null
  ACTIONTYPE_SHOW_SMP_BOX: null
  ACTIONTYPE_CLOSE_SMP_BOX: null
  ACTIONTYPE_DEACTIVATE_SMP_REQUEST_MESSAGES: null
#stores
  EVENT_STORE_CHANGED: null
#message
  EVENT_MESSAGE_INBOUND: null
  EVENT_MESSAGE_OUTBOUND: null
  EVENT_ENCRYPTED_MESSAGE_INBOUND: null
  EVENT_ENCRYPTED_MESSAGE_OUTBOUND: null
#app status
  EVENT_SHUTDOWN_APP: null
#crypto
  EVENT_SMP_OUTBOUND: null
